
### Get all todos
GET https://8sz6wtwh42.execute-api.us-east-1.amazonaws.com/prod/todos

### Create a new todo
POST https://8sz6wtwh42.execute-api.us-east-1.amazonaws.com/prod/todos
Content-Type: application/json

{
  "text": "My First AWS Lambda"
}