
### Get all todos
GET https://8mnjosxixc.execute-api.eu-north-1.amazonaws.com/prod/todos

### Create a new todo
POST https://8mnjosxixc.execute-api.eu-north-1.amazonaws.com/prod/todos
Content-Type: application/json

{
  "text": "Kolmas kerta toden sanoo"
}